# Generated by Django 5.0.7 on 2024-08-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbweb', '0004_userprofile_user_alter_userprofile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='media/default/default-icon.jpg', null=True, upload_to='media/profile_pics/'),
        ),
    ]
